$schema: vscode://schemas/color-theme
author: Dan Hedgecock
name: Tranquil
colorSpaceName: sRGB
semanticClass: theme.dark.tranquil
# Colors namespace is for all editor theming, including workbench, terminal, etc.
# These rules are contained in separate files
colors: {}
# TokenColors namespace is for syntax token theming. The generic types are themed
# here according to the Textmate naming convention and the package color semantics.
# See: http://manual.macromates.com/en/language_grammars#naming_conventions.html
# NOTE: Generic <meta> does not get a visual style, see naming conventions
tokenColors:
  # Generic <comment> matches
  - scope: comment
    settings:
      foreground: $comment
      fontStyle: italic
  # Generic <constant> matches
  # Constants are actually variables, booleans are constants
  - scope: constant
    settings:
      foreground: $constant
  # Generic <entity> match
  # Entities end up being a lot of things, most noticably class names, method names
  # The light yellow provides color without grabbing too much attention
  - scope: entity
    settings:
      foreground: $entity
  # Generic <invalid>
  - scope: invalid
    settings:
      foreground: $invalid
      fontStyle: italic bold underline
  # Generic <keyword> matches
  # Language keywords like export or return
  - scope: keyword
    settings:
      foreground: $keyword
  # Generic <markup> match
  # Base for markup languages like markdown
  - scope: markup
    settings:
      foreground: $markup
  # Generic <storage> matches
  # Includes things like variable declarations
  - scope: storage
    settings:
      foreground: $storage
  # Generic <string> match
  - scope: string
    settings:
      foreground: $string
  # Generic <support> match
  # Support is meant to be things provided by external frameworks or libraries
  - scope: support
    settings:
      foreground: $support
  # Generic <variable> matches
  - scope: variable
    settings:
      foreground: $variable
